### ISSUE TITLE
Can't run the project right away

### ISSUE THREAD

**Issue by SamTh3D3v** [KevinDockx/SecuringAspNetCore2WithOAuth2AndOIDC#1]
I've cloned the finished project, restore the nugget packages then run the project in Debug mode on IIS Express.

I am getting the following exception right away! what am i missing ?

> An unhandled exception occurred while processing the request.
> WinHttpException: A connection with the server could not be established
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> HttpRequestException: An error occurred while sending the request.
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> IOException: IDX10804: Unable to retrieve document from: 'https://localhost:44379/.well-known/openid-configuration'.
> Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()
> 
> InvalidOperationException: IDX10803: Unable to obtain configuration from: 'https://localhost:44379/.well-known/openid-configuration'.
> Microsoft.IdentityModel.Protocols.ConfigurationManager+<GetConfigurationAsync>d__24.MoveNext()
> 
> Stack Query Cookies Headers
> WinHttpException: A connection with the server could not be established
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Threading.Tasks.RendezvousAwaitable.GetResult()
> System.Net.Http.WinHttpHandler+<StartRequest>d__105.MoveNext()
> 
> Show raw exception details
> HttpRequestException: An error occurred while sending the request.
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
> System.Net.Http.DiagnosticsHandler+<SendAsync>d__2.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
> System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
> System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult()
> Microsoft.IdentityModel.Protocols.HttpDocumentRetriever+<GetDocumentAsync>d__8.MoveNext()

**Comment by KevinDockx** [comment]
Hi,

could it be that you're not starting up the IDP project?   That error states that the IDP isn't reachable.

**Comment by SamTh3D3v** [comment]
Indeed, i should've set multiple startup projects.
![image](https://user-images.githubusercontent.com/2827220/42929861-95f006fe-8b3b-11e8-9866-949e21348b8a.png)

Thanks.
